
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    expose:
      - "5000"  # expose to other containers, not host
    environment:
      FLASK_ENV: Development
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app


# volumes:
#   exmaple:


